/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rhu;
import config.dbConnect;
import config.passwordHasher;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hazel Nogra
 */
public class registrationForm extends javax.swing.JFrame {

    /** Creates new form registrationForm */
    public registrationForm() {
        initComponents();
           jPanel1.setOpaque(false);
          // Example: semi-transparent white, 50% opacity
jPanel1.setBackground(new Color(255, 255, 255, 128));  // RGBA, 128 out of 255 is 50% transparent
jPanel1.setOpaque(true);  // Must be true to paint the background color
        
        fn.setText("Enter First Name");
        fn.setForeground(Color.GRAY);

        ln.setText("Enter Last Name");
        ln.setForeground(Color.GRAY);
        
        em.setText("Enter Email");
        em.setForeground(Color.GRAY);
        
        cn.setText("Enter Contact Number");
        cn.setForeground(Color.GRAY);

        pw.setText("Enter Password");
pw.setForeground(Color.GRAY);
pw.setEchoChar((char) 0); // Show text normally

us.setText("Enter Username");
us.setForeground(Color.GRAY);

         addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentMoved(java.awt.event.ComponentEvent evt) {
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            int centerX = (screenSize.width - getWidth()) / 2;
            int centerY = (screenSize.height - getHeight()) / 2;
            setLocation(centerX, centerY);
        }
    });
    }
    
    public static String email,usname;
    public boolean duplicateCheck(){
        dbConnect dbc = new dbConnect();
        
        try{
           String query = "SELECT * FROM users WHERE u_username = '" + us.getText() + "'OR u_email = '" + em.getText() + "'";
        ResultSet resultSet = dbc.getData(query);
        if(resultSet.next()){
           
            email= resultSet.getString("u_email");
            if(email.equals(em.getText())){
                 JOptionPane.showMessageDialog(null, "Email is already used!");
                 em.setText("");
            }
            
            usname= resultSet.getString("u_username");
             if(usname.equals(us.getText())){
                 JOptionPane.showMessageDialog(null, "Username is already used!");
                  us.setText("");
            }
             return true;
            
        }else{
            return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        ty = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        togglePass2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        video = new javax.swing.JLabel();

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main bg.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(102, 51, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abt us.png"))); // NOI18N
        MainPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, -50, 200, 230));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Type:");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 110, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 110, 30));

        em.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        em.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emFocusLost(evt);
            }
        });
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emKeyReleased(evt);
            }
        });
        MainPanel.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 240, 40));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 90, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("First Name:");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 110, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Last Name:");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 110, 30));

        fn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnFocusLost(evt);
            }
        });
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        MainPanel.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 240, 40));

        ln.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnFocusLost(evt);
            }
        });
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });
        MainPanel.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 240, 40));

        pw.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwFocusLost(evt);
            }
        });
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwKeyTyped(evt);
            }
        });
        MainPanel.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 240, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        MainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Username:");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 110, 30));

        us.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        us.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usFocusLost(evt);
            }
        });
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        us.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usKeyReleased(evt);
            }
        });
        MainPanel.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 240, 40));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnFocusLost(evt);
            }
        });
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
        });
        MainPanel.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 240, 40));

        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipal Health Officer", "Staff", "Patient" }));
        ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyActionPerformed(evt);
            }
        });
        MainPanel.add(ty, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 240, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Contact No:");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 110, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        togglePass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        togglePass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePass2ActionPerformed(evt);
            }
        });
        jPanel1.add(togglePass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 30, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, 70));

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 430, 550));

        video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rhu orig.png"))); // NOI18N
        MainPanel.add(video, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -220, 1370, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       LogInForm lfm = new LogInForm();
       lfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        
       
        
   if (fn.getText().isEmpty() || ln.getText().isEmpty() || em.getText().isEmpty() 
        || cn.getText().isEmpty() || us.getText().isEmpty() || pw.getText().isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "All fields are required!");
    return; 
} 

else if (pw.getText().length() < 8) {
    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters!", 
                                  "Warning", JOptionPane.WARNING_MESSAGE);
    return;
}

else if (duplicateCheck()) {
    System.out.println("Duplicate Exists");
    JOptionPane.showMessageDialog(null, "Username or Email already exists!", 
                                  "Error", JOptionPane.ERROR_MESSAGE);
    return; 
} 

else {
    dbConnect dbc = new dbConnect(); 
    try{
    String pass = passwordHasher.hashPassword(pw.getText());

    if (dbc.insertData("INSERT INTO users (u_fname, u_lname, u_email, u_contact, u_type, u_username, u_pass, u_status) "
            + "VALUES ('" + fn.getText() + "', '" + ln.getText() + "', '" + em.getText() + "', '" 
            + cn.getText() + "', '" + ty.getSelectedItem() + "', '" + us.getText() + "', '" 
            + pass + "', 'Pending')") > 0)  
    { 
        JOptionPane.showMessageDialog(null, "Registration Success!");

        LogInForm lg = new LogInForm();
        lg.setVisible(true);
        this.dispose(); 
    } 
    else {
        JOptionPane.showMessageDialog(null, "Connection Error!", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }catch(NoSuchAlgorithmException ex){
        System.out.println(""+ex);
    }
}



        
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
             String contactNumber = cn.getText();
    
    
    if (!contactNumber.matches("\\d+")) {
        
        JOptionPane.showMessageDialog(null, "Contact Number must contain only numbers!");
        
        
        cn.setText("");
        cn.requestFocus();
    } else {
        
        System.out.println("Valid Contact Number: " + contactNumber);
    }
    }//GEN-LAST:event_cnActionPerformed

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
         String firstName = fn.getText().trim(); 

    
    if (firstName.isEmpty()) return;

    
    if (!firstName.matches("[A-Za-z]+( [A-Za-z]+)?")) {
        JOptionPane.showMessageDialog(this, "First Name must contain only letters and a single space (if needed).");

        
        fn.setText(firstName.replaceAll("[^A-Za-z ]", "").replaceAll("\\s{2,}", " ").trim());
    }
            
    }//GEN-LAST:event_fnKeyReleased

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
       String lastName = ln.getText().trim(); 

    
    if (lastName.isEmpty()) return;

    
    if (!lastName.matches("[A-Za-z]+( [A-Za-z]+)?( (Jr\\.|Sr\\.))?")) {
        JOptionPane.showMessageDialog(this, "Last Name must contain only letters, one space, and 'Jr.' or 'Sr.' if applicable!");

        
        ln.setText(lastName.replaceAll("[^A-Za-z .]", "").replaceAll("\\s{2,}", " ").trim());
    }
    }//GEN-LAST:event_lnKeyReleased

    private void emKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyReleased
      
    }//GEN-LAST:event_emKeyReleased

    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased
      String contactNumber = cn.getText().trim(); 

    
    if (!contactNumber.matches("\\d*")) { 
        JOptionPane.showMessageDialog(this, "Invalid character! Only numbers (0-9) are allowed.");
        
        
        contactNumber = contactNumber.replaceAll("[^0-9]", "");
        cn.setText(contactNumber);
    }

    
    if (contactNumber.length() > 11) {
        cn.setText(contactNumber.substring(0, 11));
    }
    }//GEN-LAST:event_cnKeyReleased

    private void usKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usKeyReleased
       String username = us.getText();

    // If text is empty, do nothing (prevents early errors)
    if (username.isEmpty()) return;

    // Check if username contains spaces
    if (username.contains(" ")) {
        JOptionPane.showMessageDialog(this, "Invalid Username! Spaces are not allowed.");
        
        // Remove spaces
        username = username.replace(" ", "");
        
        us.setText(username);
        us.requestFocus();
    }
    }//GEN-LAST:event_usKeyReleased

    private void pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyReleased
     
    }//GEN-LAST:event_pwKeyReleased

    private void tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    private void pwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyTyped
     
    }//GEN-LAST:event_pwKeyTyped

    private void emFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emFocusLost
          validateEmail();
}    

private void validateEmail() {
    String email = em.getText(); 
    if (!email.matches("^[a-zA-Z0-9._%+-]+@(gmail\\.com|edu\\.com)$")) {
        JOptionPane.showMessageDialog(null, "Invalid email! Please enter a valid Gmail!!", "Error", JOptionPane.ERROR_MESSAGE);
        em.setText(""); 
    }
    
      if (em.getText().trim().isEmpty()) {
        em.setText("Enter Email");
        em.setForeground(Color.GRAY);
   
        
    }
    }//GEN-LAST:event_emFocusLost

    private void fnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFocusGained
         if (fn.getText().equals("Enter First Name")) {
        fn.setText("");
        fn.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_fnFocusGained

    private void fnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFocusLost
         if (fn.getText().trim().isEmpty()) {
        fn.setText("Enter First Name");
        fn.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_fnFocusLost

    private void lnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFocusGained
         if (ln.getText().equals("Enter Last Name")) {
        ln.setText("");
        ln.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_lnFocusGained

    private void lnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFocusLost
       if (ln.getText().trim().isEmpty()) {
        ln.setText("Enter Last Name");
        ln.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_lnFocusLost

    private void emFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emFocusGained
        if (em.getText().equals("Enter Email")) {
        em.setText("");
        em.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_emFocusGained

    private void cnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnFocusGained
         if (cn.getText().equals("Enter Contact Number")) {
        cn.setText("");
        cn.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_cnFocusGained

    private void cnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnFocusLost
        if (cn.getText().trim().isEmpty()) {
        cn.setText("Enter Contact Number");
        cn.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_cnFocusLost

    private void pwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFocusGained
         if (String.valueOf(pw.getPassword()).equals("Enter Password")) {
        pw.setText("");
        pw.setForeground(Color.BLACK);
        pw.setEchoChar('*'); // Hide characters for password input
    }
    }//GEN-LAST:event_pwFocusGained

    private void pwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFocusLost
         if (pw.getPassword().length == 0) {
        pw.setText("Enter Password");
        pw.setForeground(Color.GRAY);
        pw.setEchoChar((char) 0); // Show text normally
    }
    }//GEN-LAST:event_pwFocusLost

    private void usFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usFocusGained
         if (us.getText().equals("Enter Username")) {
        us.setText("");
        us.setForeground(Color.BLACK); // Set text to black when user types
    }
    }//GEN-LAST:event_usFocusGained

    private void usFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usFocusLost
         if (us.getText().trim().isEmpty()) {
        us.setText("Enter Username");
        us.setForeground(Color.GRAY); // Keep placeholder gray
    }
    }//GEN-LAST:event_usFocusLost

    private void togglePass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePass2ActionPerformed
        if (togglePass2.isSelected()) {
            pw.setEchoChar((char) 0); // Show password
            togglePass2.setText("Hide");
        } else {
            pw.setEchoChar('*'); // Hide password
            togglePass2.setText("Show");
        }
    }//GEN-LAST:event_togglePass2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    private javax.swing.JPasswordField pw;
    private javax.swing.JToggleButton togglePass2;
    private javax.swing.JComboBox<String> ty;
    private javax.swing.JTextField us;
    private javax.swing.JLabel video;
    // End of variables declaration//GEN-END:variables

}
