/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rhu.LogInForm;
import rhu.registrationForm;
import static rhu.registrationForm.email;
import static rhu.registrationForm.usname;

/**
 *
 * @author Hazel Nogra
 */
public class createUserForm extends javax.swing.JFrame {

    /**
     * Creates new form createUserForm
     */
    public createUserForm() {
        initComponents();
    }
    
    public boolean duplicateCheck(){
        dbConnect dbc = new dbConnect();
        
        try{
           String query = "SELECT * FROM users WHERE (u_username = '" + us.getText() + "'OR u_email = '" + em.getText() + "'";
        ResultSet resultSet = dbc.getData(query);
        if(resultSet.next()){
           
            email= resultSet.getString("u_email");
            if(email.equals(em.getText())){
                 JOptionPane.showMessageDialog(null, "Email is already used!");
                 em.setText("");
            }
            
            usname= resultSet.getString("u_username");
             if(usname.equals(us.getText())){
                 JOptionPane.showMessageDialog(null, "Username is already used!");
                  us.setText("");
            }
             return true;
            
        }else{
            return false;
        }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }
    
    public boolean updateCheck(){
    dbConnect dbc = new dbConnect();
    try{
        String userId = usid.getText();
        if(userId == null || userId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Error, user id is empty");
            return true;
        }
        String query = "SELECT * FROM users WHERE (u_username = '" + us.getText() + "' OR u_email = '" + em.getText() + "') AND u_id != '" + userId + "'";

        ResultSet resultSet = dbc.getData(query);
        if(resultSet.next()){
            email= resultSet.getString("u_email");
            if(email.equals(em.getText())){
                JOptionPane.showMessageDialog(null, "Email is already used!");
                em.setText("");
            }

            usname= resultSet.getString("u_username");
            if(usname.equals(us.getText())){
                JOptionPane.showMessageDialog(null, "Username is already used!");
                us.setText("");
            }
            return true;

        }else{
            return false;
        }
    }catch(SQLException ex){
        System.out.println(""+ex);
        return false;
    }
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Navigation = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        ty = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        uss = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        usid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navigation.setBackground(new java.awt.Color(255, 255, 255));
        Navigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(102, 51, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abt us.png"))); // NOI18N
        Navigation.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -40, 270, 230));

        jLabel13.setBackground(new java.awt.Color(102, 51, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/med.png"))); // NOI18N
        Navigation.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 520, 620));

        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Navigation.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 40));

        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Navigation.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, 30));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        Navigation.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, 30));

        clear.setText("CLEAR");
        Navigation.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 30));

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Navigation.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 90, 30));

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        Navigation.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 90, 30));

        MainPanel.add(Navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 580));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("User Status");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 110, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN");
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 400, 70));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, 30));

        em.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        em.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emKeyReleased(evt);
            }
        });
        MainPanel.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 240, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("User ID");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 110, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Last Name:");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 110, 30));

        fn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        MainPanel.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 240, 40));

        ln.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });
        MainPanel.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 240, 40));

        pw.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwKeyTyped(evt);
            }
        });
        MainPanel.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 240, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        MainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 110, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Username:");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 110, 30));

        us.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        us.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usKeyReleased(evt);
            }
        });
        MainPanel.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 240, 40));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
        });
        MainPanel.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 240, 40));

        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipal Health Officer", "Staff", "Frontdesk" }));
        ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyActionPerformed(evt);
            }
        });
        MainPanel.add(ty, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 240, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Contact No:");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 110, 30));

        uss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        uss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ussActionPerformed(evt);
            }
        });
        MainPanel.add(uss, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 240, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Type:");
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 110, 30));

        usid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usid.setEnabled(false);
        usid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usidActionPerformed(evt);
            }
        });
        usid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usidKeyReleased(evt);
            }
        });
        MainPanel.add(usid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 240, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("First Name:");
        MainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void emKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emKeyReleased
        String email = em.getText().trim(); // Trim spaces at start/end

        // If text is empty, do nothing (prevents early errors)
        if (email.isEmpty()) return;

        // Show error only when Enter key is pressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!email.contains("@")) {
                JOptionPane.showMessageDialog(this, "Invalid Email! An '@' is required.");
            }
        }
    }//GEN-LAST:event_emKeyReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       dbConnect dbc = new dbConnect();   
       if (fn.getText().trim().isEmpty() || ln.getText().trim().isEmpty() || em.getText().trim().isEmpty()
        || cn.getText().trim().isEmpty() || us.getText().trim().isEmpty() || pw.getPassword().length == 0) {

    JOptionPane.showMessageDialog(null, "All Fields are Required!");
    return; // Exit the method if validation fails
}

else if (pw.getPassword().length < 8) {
    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters!",
            "Warning", JOptionPane.WARNING_MESSAGE);
    return;
}

else if (duplicateCheck()) {
    System.out.println("Duplicate Exists");
    return;
} 


else if (dbc.insertData("INSERT INTO users (u_fname, u_lname, u_email, u_contact, u_type, u_username, u_pass, u_status) "
        + "VALUES('" + fn.getText().trim() + "', '" + ln.getText().trim() + "', '" + em.getText().trim() + "', '"
        + cn.getText().trim() + "', '" + ty.getSelectedItem().toString() + "', '" + us.getText().trim() + "', '"
        + new String(pw.getPassword()) + "', '" + uss.getSelectedItem().toString() + "')") > 0) {

    JOptionPane.showMessageDialog(null, "Successfully Registered");

    adminUsers usd = new adminUsers();
    usd.setVisible(true);

    this.dispose();
} else {
    JOptionPane.showMessageDialog(null, "Registration failed. Please try again.");
}

    }//GEN-LAST:event_addActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
        String firstName = fn.getText().trim(); // Trim spaces at start/end

        // If text is empty, do nothing (prevents early errors)
        if (firstName.isEmpty()) return;

        // Allow one or two names (letters only, single space allowed)
        if (!firstName.matches("[A-Za-z]+( [A-Za-z]+)?")) {
            JOptionPane.showMessageDialog(this, "First Name must contain only letters and a single space (if needed).");

            // Remove invalid characters (only letters and spaces allowed)
            fn.setText(firstName.replaceAll("[^A-Za-z ]", "").replaceAll("\\s{2,}", " ").trim());
        }

    }//GEN-LAST:event_fnKeyReleased

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
        String lastName = ln.getText().trim(); // Trim spaces at start/end

        // If text is empty, do nothing (prevents early errors)
        if (lastName.isEmpty()) return;

        // Allow one or two names with optional "Jr." or "Sr."
        if (!lastName.matches("[A-Za-z]+( [A-Za-z]+)?( (Jr\\.|Sr\\.))?")) {
            JOptionPane.showMessageDialog(this, "Last Name must contain only letters, one space, and 'Jr.' or 'Sr.' if applicable!");

            // Remove invalid characters (only letters, spaces, and "." allowed)
            ln.setText(lastName.replaceAll("[^A-Za-z .]", "").replaceAll("\\s{2,}", " ").trim());
        }
    }//GEN-LAST:event_lnKeyReleased

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    private void pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyReleased

    }//GEN-LAST:event_pwKeyReleased

    private void pwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyTyped

    }//GEN-LAST:event_pwKeyTyped

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    private void usKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usKeyReleased
        String username = us.getText();

        // If text is empty, do nothing (prevents early errors)
        if (username.isEmpty()) return;

        // Check if username contains spaces
        if (username.contains(" ")) {
            JOptionPane.showMessageDialog(this, "Invalid Username! Spaces are not allowed.");

            // Remove spaces
            username = username.replace(" ", "");

            us.setText(username);
            us.requestFocus();
        }
    }//GEN-LAST:event_usKeyReleased

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        String contactNumber = cn.getText();

        // Check if the text contains only digits
        if (!contactNumber.matches("\\d+")) {
            // Show an error message
            JOptionPane.showMessageDialog(null, "Contact Number must contain only numbers!");

            // Clear the field or reset focus
            cn.setText("");
            cn.requestFocus();
        } else {
            // Optionally handle valid input
            System.out.println("Valid Contact Number: " + contactNumber);
        }
    }//GEN-LAST:event_cnActionPerformed

    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased
        String contactNumber = cn.getText().trim(); // Trim spaces

        // Check if input contains anything other than digits
        if (!contactNumber.matches("\\d*")) {
            JOptionPane.showMessageDialog(this, "Invalid character! Only numbers (0-9) are allowed.");

            // Remove non-numeric characters
            contactNumber = contactNumber.replaceAll("[^0-9]", "");
            cn.setText(contactNumber);
        }

        // Limit to 11 characters
        if (contactNumber.length() > 11) {
            cn.setText(contactNumber.substring(0, 11));
        }
    }//GEN-LAST:event_cnKeyReleased

    private void tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyActionPerformed

    private void ussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ussActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ussActionPerformed

    private void usidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usidActionPerformed

    private void usidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_usidKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        adminUsers adr = new adminUsers();
        adr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
   
if(fn.getText().isEmpty() || ln.getText().isEmpty() || em.getText().isEmpty()
   || us.getText().isEmpty() || pw.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "All fields are required!");
} else if(pw.getText().length() < 8) {
    JOptionPane.showMessageDialog(null, "Password character should be 8 above");
    pw.setText("");
} else if(updateCheck()) {
    System.out.println("Duplicate Exist");
} else {
   dbConnect dbc = new dbConnect();
dbc.updateData("UPDATE users SET u_fname = '" + fn.getText() + "', "
             + "u_lname = '" + ln.getText() + "', "
             + "u_email = '" + em.getText() + "', u_contact = '" + cn.getText() + "', "
             + "u_username = '" + us.getText() + "', "
             + "u_pass = '" + pw.getText() + "', "
             + "u_type = '" + ty.getSelectedItem() + "', "
             + "u_status = '" + uss.getSelectedItem() + "' "
             + "WHERE u_id = '" + usid.getText() + "'");

}



       
    }//GEN-LAST:event_updateActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
       
       


    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Navigation;
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    public javax.swing.JTextField cn;
    private javax.swing.JButton delete;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField ln;
    public javax.swing.JPasswordField pw;
    private javax.swing.JButton refresh;
    public javax.swing.JComboBox<String> ty;
    public javax.swing.JButton update;
    public javax.swing.JTextField us;
    public javax.swing.JTextField usid;
    public javax.swing.JComboBox<String> uss;
    // End of variables declaration//GEN-END:variables
}
